language: node_js
sudo: required
node_js:
  - "10"
script:
  - npm run lint
  - bin/index.js cable
  - bin/index.js stop
  - bin/index.js throttle --up 330 --down 780 --rtt 200
  - bin/index.js stop
  - bin/index.js --rtt 200 --localhost
  - bin/index.js stop --localhost
notifications:
  slack:
    secure: CDiXaDmWzsA2IpKZiST744uZooaoTuJ+qTMWElSWsHIp6cA/mbOLcZGsmhemmKaYvKl7ASF8doJrCaBinmy59Unzs0Er/Kfp1gwlQ4wpbOk3Bj072bgM3r8ipIunnEa0S6ynGK6n2OtUZOlnmUsP1dha9ndRVsT+vK4W9xqzsl0grRXcvv+56vkzvcPGq7rATMnbIpT4DvbzgX0NoAyZZMz6/R1CPnGVirp/7dHB6+OYkt6wooM0yCJS32G1JsjoZMwHSqs697pVOsOziO6LZ9NlBRp5Fv0SsIFQAroX6zqOkWjtjR8sPs8MDqw8K2pM7Wi4NKgV1qUTqi1a9ScfgRZ2cg9o2hKsPHBSpYq1v4ijlNm7O4gAs0t0XupJtrUS9gi1cAnHKT0/JJDLXRZOmAYIeSH76WnefAEpcXGKXKWqOQVlG4/cPbD9Xi3WswWVUoxrFCWM+ORGdfM/qMbUtBWfD1HCM13Sqv/DDX5F2gFGQZda1WjWZQ11HEnZWFhGvT7kDYbPc816XMP26gpq3xxsi9vtfmo09RvFRk2mTwlXAK8ppS40GeAlNOolxWjPGrWZBzwIBVUmRiyKZf4KgIkBD3z9woDQnoFr+FWwe1Yi0uqqhov1iI8iu/xhjdEP8PDyfy1FuoF4mlE0xqBAFqGx55SWFKxlMaBixRqoYf0=
